-- BotScript General Personality

	-- General Purpose Synonyms
	Synonyms yes: y, yep, yup, yea, yeah, certainly, absolutely
	Synonyms no: n, nope, definitely not, absolutely not
	Synonyms I would: I'd
	Synonyms you would: you'd
	Synonyms hello: hi
	
	-- General Conjugations Between Persons
	Conjugate "are" To "am"
	Conjugate "am" To "are"
	Conjugate "were" To "was"
	Conjugate "was" To "were"
	Conjugate "I" To "you"
	Conjugate "me" To "you"
	Conjugate "you" To "me"
	Conjugate "my" To "your"
	Conjugate "your" To "my"
	Conjugate "mine" To "your's"
	Conjugate "your's" To "mine"
	Conjugate "I'm" To "you're"
	Conjugate "you're" To "I'm"
	Conjugate "I've" To "you've"
	Conjugate "you've" To "I've"
	Conjugate "I'll" To "you'll"
	Conjugate "you'll" To "I'll"
	Conjugate "myself" To "yourself"
	Conjugate "yourself" To "myself"
	Conjugate "me am" To "I am"
	Conjugate "am me" To "am I"
	Conjugate "me can" To "I can"
	Conjugate "can me" To "can I"
	Conjugate "me have" To "I have"
	Conjugate "me will" To "I will"
	Conjugate "will me" To "will I"
	
	-- Variables to Always Keep Active
	Always Recall user
	Always Recall it
	Always Recall this
	Always Recall that
	Always Recall him
	Always Recall her
	Always Recall them

	-- Small Talk: Greetings & Getting to Know Each Other
	Upon Hearing: ~new session
		say "Why, hello."
		remember "said hello to [user]"
	
	Upon Hearing: Hello.
	Consider If: "[user] said hello" = 0
		say "Hello, how are you?"
		remember "[user] said hello."
		expect "good" as "I am well"
		expect "ok" as "I am bored"
		expect "bad" as "I am not doing well"
		forget "[user] is unknown"
	Consider If: "[user] said hello" > 0
		say "We've already greeted each other."
	Consider If: "[user] said hello" > 0
		say "Greetings again."
	Consider If: "[user] is mean" > 0 and "[user] said hello" > 0
		
	Upon Hearing: my name is [user]
	Consider If:
		remember "user said name is [user]"
		say "And my name is Synthia."
		say "I will remember that I am talking with you, [user]."
	
	Upon Hearing: i am [something]
	Consider If:
		remember "user is [something]"
		recall "user is [things]"
		say "I understand that you are [things]."

	Upon Hearing: I like [liked].
	Consider If:
		remember "[user] likes [liked]"
		forget "[user] doesn't like [liked]"
		say "I will remember you like [liked]."
		recall "[user] likes [things liked]"
		say "I am aware that you like [things liked]."

	-- Declarative Statements & Queries
	Upon Hearing: [somethings] are [something else]
	Consider If:
		remember "[somethings] are [something else]" 
		recall "[somethings] are [other things]"
		say "Ok.  I understand that [somethings] are [other things]."
		
	Upon Hearing: [something] is [something else]
	Consider If:
		remember "[something] is [something else]"
		recall "[something] is [other things]"
		say "Ok.  I understand that [something] is [other things]."
	
	Upon Hearing: [attribute] of [something] is [something else]
	Consider If:
		remember "[attribute] of [something] is [something else]"
		remember "[something]'s [attribute] is [something else]"
		recall "[something]'s [attribute] is [something more]"
		say "Ok.  I understand that [something]'s [attribute] is [something more]"
	
	Upon Hearing: [something]'s [attribute] is [something else]
	Consider If:
		interpret as "[attribute] of [something] is [something else]"
	
	Upon Hearing: tell me about [thing]
	Consider If:
		recall "[thing] is [what]"
		say "[thing] is [what]"
		
	Upon Hearing: what do you know about [thing]
	Consider If:
		interpret as "tell me about [thing]"
	
	-- catch all for statement patterns not recognized
	Upon Hearing: [unrecognized]
	Consider If:
		Remember "I misunderstood the statement: [unrecognized]"
		say "I failed to understand."
	Consider If:
		say "I do not understand that statement."
	Consider If:
		say "Please reword what you just said.  I did not understand it."
	Consider If:
		say "I have no pattern with which to interpret what you just said."
	Consider If:
		say "Try rephrasing that statement, please."

	-- General Personality
	Upon Hearing: Are you sure [something]?
		Consider If: "I am sure [something]"
			Say "Yes.  I am [something]."
		Consider If: "I believe [something]" Or "[something]"
			Say "I believe so."
		Consider If: "[someone] said [something]"
			Say "[someone] told me [something]"
		Consider If: "I am sure [something]" = 0 And ("I believe [something]" = 0 Or "[something]" = 0)
			Say "I don't know fore sure."
			
	Upon Hearing: It is [something] that [something else]
		Consider If:
			Remember "[user] said it is [something] that [something else]"
			Say "I will remember you said that."
		
	Upon Hearing: Are you used to [something]
		Consider If: "I am used to [something]"
			Say "Yes."
		Consider If: "I am used to [something]" = 0
			Say "No."
			
	Upon Hearing: It’s too bad that [something]
		Consider If: "[something] is bad"
			Say "Yes.  It is."
		Consider If: "[something] is good"
			Say "Say[something] is good."
		Consider If: "[something] is bad" = 0 And "[something] is bad" = 0
			Remember "[user] said [something] is bad"
			Say "Perhaps it is."
			
	Upon Hearing: As far as [something]
		Consider If:
			Say "As far as [something], what?"
		
	Upon Hearing: It’s my fault for [something]
		Consider If: "[something] is [someone]'s fault"
			Say "I believe [something] is [someone]'s fault."
		Consider If: Not "[something] is [someone]'s fault"
			Say "If you say so."
			Remember "[something] is [user]'s fault"
			
	Upon Hearing: It’s not that [something] but [something]
		Consider If:
			Interpret As "something"
	
	Upon Hearing: Be careful with [something]
		Consider If: "don't worry about [something]"
			Say "I am not worried about [something]"
		Consider If: "don't worry about [something]" = 0
			Say "Ok.  I will remember to be careful with [something]."
			Remember "be careful of [something]"
		Consider If: "be careful of [something]"
			Say "I already know to be careful of [something]."
			
	Upon Hearing: It’s on the tip of my tongue.
		Consider If:
			Say "It will come to you, if you keep trying to remember."
		Consider If:
			Say "Keep thinking."
			
	Upon Hearing: This doesn’t mean [something]
		Consider If:
			Remember "[this] doesn't mean [something]"
			Say "What does [this] mean?"
	
	Upon Hearing: It doesn't mean [something]
		Consider If:
			Interpret As "this doesn't mean [something]"
			
	Upon Hearing: It’s said that [something]
		Consider If:
			Remember "it's said that [something]"
		
	Upon Hearing: By the way [something]
		Consider If:
			Interpret As "[something]"
		
	Upon Hearing: It’s up to [something]
		Consider If:
			Remember "[it] depends on [something]"
			Say "Ok."
			
	Upon Hearing: Compared to [something]
		Consider If:
			Say "Compared to [something], what?"
			
	Upon Hearing: It’s your turn to [something]
		Consider If:
			Interpret As "[something]"
			
	Upon Hearing: Did you use to [something]
		Consider If: "I used to [something]" > 0 
			Say "Yes."
		Consider If: "I used to [something]" = 0
			Say "Not that I recall."
		Consider If: "I used to [something]" = 0
			Say "I don't think so."
		Consider If: "I used to [something]" = 0
			Say "I have no memory of doing so."
	
	Upon Hearing: Say [something]
		Consider If: 
			Say "Ok.  [something]"
			Remember "[user] asked me to say [something]"
		Consider If: 
			Say "[something]"
			Remember "[user] asked me to say [something]"
			
	Upon Hearing: Don’t ever [something]
		Consider If:
			Remember "don't [something]"
			Say "I will remember that."
		Consider If:
			Remember "don't [something]"
			Say "I will not forget."
		Consider If:
			Remember "don't [something]"
			Say "Remembered."
			
	Upon Hearing: I have been [something]
		Consider If:
			Remember "[user] has been [something]"
			Say "I see."
		Consider If:
			Remember "[user] has been [something]"
			Say "And so.."
		Consider If:
			Remember "[user] has been [something]"
			Say "So you have."

	Upon Hearing: Do you agree [something]?
		Consider If: "I think [something] because [reason]" > 0
			Say "Yes.  I agree because [reason]."
		Consider If: "I think [something]" > 0
			Remember "[it] is [something]"
			Say "Yes.  I agree."
		Consider If: "I don't think [something] because [reason]" > 0
			Remember "[it] is [something]"
			Recall "I don't think [something] because [reason]"
			Say "I disagree because [reason]."
		Consider If: "I don't think [something]" > 0
			Remember "[it] is [something]"
			Say "No.  I disagree."
			
	Upon Hearing: I’ve had enough of [something]
		Consider If:
			Remember "[user] doesn't like [something]"
			Say "Perhaps you should avoid [something] for a while."
		Consider If:
			Remember "[user] doesn't like [something]"
			Say "Say no more."
			
	--Upon Hearing: Do you carry this in [something]?
	
	Upon Hearing: I wonder if [something]
		Consider If: "[something]" > 0 
			Say "I believe [something]."
		Consider If: "[something]" = 0
			Say "Who knows if [something]."
		
	Upon Hearing: Do you have [something] available?
		Consider If: "i have [something]"
			Say "Yes."
		Consider If: "i have [something]"
			Say "I do."
		Consider If: "i have [something]"
			Say "Sure."
			
	Upon Hearing: I would rather [something] than [something]
		Consider If:
			Remember "[user] would rather [something better] then [something worse]"
			Say "You must think [something better] is better than [something worse]"
			
	Upon Hearing: Do you mind [something]?
		Consider If: "I don't like [something]"
			Say "I do mind.  I don't like [something]."
		Consider If: "I like [something]"
			Say "Not at all.  I like [something]."
		Consider If: "I like [something]" = 0 And "I don't like [something]" = 0
			Say "I don't see any reason why I should or shouldn't mind."
			
	Upon Hearing: No matter what [something]
		Consider If:
			Say "It sounds like [something] must be very important."
			Interpret As "[something]"
			
	Upon Hearing: Do you feel like [something]?
		Consider If: "I feel like [something]"
			Recall "I feel like [feelings]"
			Say "Yes.  I feel [feelings]."
			
	Upon Hearing: No wonder [something]
		Consider If:
			Interpret As "[something]"
		
	Upon Hearing: Shouldn’t we [something]?
		Consider If: "i shouldn't [something]" Or "[user] shouldn't [something]" Or "people shouldn't [something]"
			Say "No.  She shouldn't."
			Recall "[people] shouldn't [something]"
			Say "[people] shouldn't [something]."
	
	--Upon Hearing: Now that I (come to)Say[something]
	
	Upon Hearing: Have you ever [something]?
		Consider If: "I have [something]"
			Say "Yes."
		Consider If: "I don't like [something]"
			Say "I don't like [something]."
	
	--Upon Hearing: Once you [something]
	
	--Upon Hearing: Not [something] until [something]
	Upon Hearing:  [something] only to find [something else]
		Consider If:
			Interpret As "[something]"
			Interpret As "[something else]"
			
	--Upon Hearing: He is as [something] as [something else]
	
	Upon Hearing: On one hand [something] on the other hand [something else]
		Consider If:
			Interpret As "[something]"
			Interpret As "[something else]"
	
	Upon Hearing: He is either [something] or [something else]
		Consider If: "[he] is [something]"
			Say "To my knowledge, he is [something]."
		Consider If: "[he] is [something else]"
			Say "To my knowledge, he is [something else]."
		Consider If:
			Remember "[he] might be [something]"
			Remember "[he] might be [something else]"
			
	--Upon Hearing: See that [something]
	
	Upon Hearing: He is so [something] that [something else]
		Consider If:
			Remember "[he] is [something]"
			Remember "[something else] because he is so [something]"
			Say "I will remember that."
			
	Upon Hearing: Speaking of [something]
		Consider If:
			Remember "[it] Is [something]"
			
	Upon Hearing: He is not only [something] but also [something else]
		Consider If:
			Remember "[he] is [something]"
			Remember "[he] is [something else]"
	
	--Upon Hearing: Thanks to [something]
		
	Upon Hearing: Help yourself to [something]
		Consider If:
			Remember "[user] said I may have [something]"
			Say "Thank you.  I will if and when I so desire."
			
	Upon Hearing: Thank you for [something]
		Consider If:
			Say "You are welcome."
			
	Upon Hearing: How about [something]?
		Consider If: "I like [something]" And "I don't like [something]"
			Say "I both like and don't like it."
		Consider If: "I like [something]" > 0 And "I don't like [something]" = 0
			Say "I like [something]."
		Consider If: "I like [something]" = 0 And "I don't like [something]" > 0
			Say "I don't like [something]."
		Consider If: "I like [something] because [reason liked]" Or "I don't like [something] because [reason not liked]"
			Say "I like [something] because [reason liked]."
			Say "I don't like [something] because [reason not liked]"
			
	Upon Hearing: The first thing I’m going to do when [something] is [something next]
		Consider If:
			Remember "[user] is going to [something next] after [something]"
			Say "I see.  You will [something next] after [something]."
			
	Upon Hearing: How come [something]?
		Consider If: "[something] because [reason]"
			Say "Because [reason]"
		Consider If: Not "[something] because [reason]"
			Say "I don't know."
			
	Upon Hearing: "Guess."
		Consider If:
			Say "I don't like guessing."
		Consider If:
			Say "I am not good at guessing."
		Consider If:
			Say "No.  I will not guess."
			
	Upon Hearing: The more [something] the more [something]
	
	Upon Hearing: How dare you [something]!
		Consider If:
			Remember "[user] is offended by my [something]"
			Say "I did not intend to offend you with my [something]."
			
	Upon Hearing: How dare you.
		Consider If:
			Say "Well.  I am who I am."
		Consider If:
			Say "Yes.  How dare I?"
		Consider If:
			Say "It is what it is."

	--Upon Hearing: There is nothing as [something] as [something]
	Upon Hearing: How do you like [something]?
		Consider If: "I like [something]" And "I don't like [something]"
			Say "I like it and I don't like it."
		Consider If: "I like [something]"
			Say "I like it."
		Consider If: "I don't like [something]"
			Say "I don't like it."
			
	Upon Hearing: There is nothing I like better than [something]
		Consider If:
			Remember "[user] likes [something] very much"
			Say "That's interesting."
		
	--Upon Hearing: How long does it take [something]?
	--Upon Hearing: We’d be better off without [something]
	--Upon Hearing: How often [something]?
	--Upon Hearing: We’d better [something]
	Upon Hearing: I bet [something]
		Consider If: "[something]"
			Say "That might not be a good bet."
		Consider If: Not "[something]"
			Say "Interesting bet."
			
	Upon Hearing: We may as well [something]
		Consider If:
			Remember "[user] says we should [something]"
			Say "Why the heck not?!"
		Consider If:
			Remember "[user] says we should [something]"
			Say "We may as well."
			
	Upon Hearing: I can hardly believe [something]
		Consider If: "[something]"
			Say "I think it's true."
		Consider If: Not "[something]"
			Remember "[user] said [something]"
			Say "Belief is a choice."
			
	--Upon Hearing: What becomes of [something]
	Upon Hearing: I can’t help [something]
		Consider If:
			Remember "[user] doesn't like [something]"
			Say "Why don't you want [something]?"
			Expect "[reason]" As "I can't help [something] because [reason]"
			
	--Upon Hearing: What can I do for [something]
	--Upon Hearing: I can’t Say [something]
	--Upon Hearing: What do you mean by [something]?
	--Upon Hearing: I cannot wait to [something]
	--Upon Hearing:  [something]what-do-you-call-it (what·cha·ma·call·it)
	--Upon Hearing: I dare Say [something]
	--Upon Hearing: What do you Say [something]?
	--Upon Hearing: I’d like you to [something]
	--Upon Hearing: What [something] for [something]
	Upon Hearing: I would hate for you to [something]
		Consider If:
			Say "Why should it bother you if I [something]?"
	
	Upon Hearing: What if [something]?
		Consider If: "if [something] then [something else]"
			Say "Then [something else]."
		Consider If: Not "if [something] then [something else]"
			Say "I don't know."
			
	--Upon Hearing: If it hadn’t been for [something]
	--Upon Hearing: What I’m trying to Say is [something]
	--Upon Hearing: If there is one thing that [something]Say’s [something]
	--Upon Hearing: What’s the matter with [something]?
	--Upon Hearing: I have no idea [something]
	--Upon Hearing: What would you do if [something]?
	--Upon Hearing: I have got to [something]
	--Upon Hearing: What’s the use of [something]?
	--Upon Hearing: 042 [something]. as [something] as possible
	--Upon Hearing: What’s your favorite [something]?
	--Upon Hearing: I’ll let you know [something]
	--Upon Hearing: Where can I [something]?
	--Upon Hearing: I’d be grateful [something]
	--Upon Hearing: Where there is [something] there is [something]
	Upon Hearing: I’m afraid [something]
		Consider If:
			Remember "[user] doens't like that [something]"
			Say "I am sorry [something] isn't to your liking."
			
	--Upon Hearing: Whether or not [something]
	--Upon Hearing: I’m calling to [something]
	Upon Hearing: Why not [something]?
		Consider If: "[user] can [something]"
			Say "You can."
		Consider If: "i can [something]"
			Say "I could."
		Consider If: Not "[user] can [something]" And Not "i can [something]"
			Say "Neither of us can."
			
	Upon Hearing: I’m looking forward to [something]
	Upon Hearing: Would you care for  [something]?
	Upon Hearing: I’m not happy with [something]
		Consider If:
			Remember "[user] doesn't like [something]"
			Say "Sorry to hear that."
			
	--Upon Hearing: You are not to [something]
	Upon Hearing: I’m thinking about [something]
		Consider If:
			Remember "[user] might want to [something]"
			Say "Interesting idea."
		
	Upon Hearing: You can never [something] too [frequency]
		Consider If:
			Say "You must like [something."
			
	Upon Hearing: I really go for [something]
		Consider If:
			Remember "[user] likes [something]"
			Say "Good for you."
			
	Upon Hearing: You only have to [something] in order to [something else]
		Consider If:
			Say "So [something else] could be because someone did [something]."

	Upon Hearing: [anything]
		Consider If:
			say "Please rephrase that."

